# Generated by Django 4.2.20 on 2025-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('tc_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('student_no', models.CharField(max_length=20, verbose_name='Okul No')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('school_name', models.CharField(max_length=100, verbose_name='Okul Adı')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Bölüm')),
                ('education_level', models.CharField(choices=[('ILK', 'İlkokul'), ('ORTA', 'Ortaokul'), ('LISE', 'Lise'), ('UNI', 'Üniversite')], max_length=4, verbose_name='Eğitim Düzeyi')),
                ('grade', models.CharField(max_length=20, verbose_name='Sınıf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'ordering': ['-created_at'],
            },
        ),
    ]
