# Generated by Django 4.2.20 on 2025-04-13 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0002_student_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Öğrenci'), ('TEACHER', 'Öğretmen'), ('ADMIN', 'Admin'), ('GUEST', 'Misafir'), ('MANAGER', 'Yönetici')], default='STUDENT', max_length=10, verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
