# Generated by Django 4.2.20 on 2025-04-13 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_add_user_and_role'),
        ('students', '0003_student_role_student_user'),
    ]

    operations = [
    ]
