# Generated by Django 4.2.20 on 2025-04-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_merge_20250413_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Öğrenci'), ('GUEST', 'Misafir')], default='STUDENT', max_length=10, verbose_name='Rol'),
        ),
    ]
