# Generated by Django 4.2.20 on 2025-04-13 20:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Açık Tema'), ('dark', 'Koyu Tema'), ('system', 'Sistem Teması')], default='light', max_length=20, verbose_name='Tema')),
                ('notifications_enabled', models.BooleanField(default=True, verbose_name='Bildirimler Aktif')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='E-posta Bildirimleri')),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce')], default='tr', max_length=10, verbose_name='Dil')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Ayarı',
                'verbose_name_plural': 'Kullanıcı Ayarları',
            },
        ),
    ]
