# Generated by Django 4.2.20 on 2025-04-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('tc_no', models.CharField(max_length=11, unique=True, verbose_name='TC Kimlik No')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('branch', models.CharField(choices=[('MAT', 'Matematik'), ('FEN', 'Fen Bilimleri'), ('TUR', 'Türkçe'), ('SOS', 'Sosyal Bilgiler'), ('ING', 'İngilizce'), ('BIL', 'Bilişim'), ('DIG', 'Diğer')], max_length=3, verbose_name='Branş')),
                ('school_name', models.CharField(max_length=100, verbose_name='Okul Adı')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Deneyim (Yıl)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Öğretmen',
                'verbose_name_plural': 'Öğretmenler',
                'ordering': ['-created_at'],
            },
        ),
    ]
